services:
  api:
    volumes:
      - ./src:/app/src
      - ./templates:/app/templates
      - ./static:/app/static
    command: uvicorn assistx.api:app --host 0.0.0.0 --port 8000 --reload
  worker:
    volumes:
      - ./src:/app/src