version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: phone-log-api
    env_file: .env
    ports: ["8888:8000"]
    volumes:
      - ./data:/data
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:5.20-community
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_default__advertised__address=neo4j
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=1G
      - NEO4J_apoc_import_file_enabled=true
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - ./db:/var/lib/neo4j/import

volumes:
  neo4j-data: {}
  neo4j-logs: {}
